name: Run Android Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 6" # Run every Saturday at 3 PM Cairo time

jobs:
  android-tests:
    name: Run Android Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: '31.0.0'
        target: 'android-31'

    - name: Install AVD Manager
      run: sdkmanager "system-images;android-31;default;x86_64"

    - name: List available AVDs
      run: |
        avdmanager list avd

      # Set up Android Emulator
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: Pixel_4_API_31
          emulator-options: "-no-audio -no-window -gpu swiftshader_indirect"
          startup-timeout: 600

      # Run Android Tests
      - name: Run Android Tests
        run: npm run android:test

      # Terminate Emulator
      - name: Terminate Emulator
        run: adb -s emulator-5554 emu kill || true
